spring:
  application:
    name: PManager
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  #  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/pmanagerdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
  servlet:
    context-path: /
app:
  pageSize: 3


